version: '2.1'
orbs:
  node: circleci/node@5.0.3
jobs:
  install-node-example:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/install:
          install-yarn: false
          node-version: '16.14'
      - run: sudo npm install -g npm@latest
      - node/install-packages:
          cache-path: ~/project/node_modules
          override-ci-command: npm install
      - run: npm run test
workflows:
  test_my_app:
    jobs:
      - install-node-example

# version: 2.1
# orbs:
#   node: circleci/node@5.0.3
# jobs:
#   build:
#     working_directory: ~/FindYourSpace
#     executor: node/default
#     steps:
#       - checkout
#       - run: sudo npm install -g npm@latest
#       - node/install-packages:
#           app-dir: ~/FindYourSpace
#           cache-path: node_modules
#           override-ci-command: npm i
#       - persist_to_workspace:
#           root: .
#           paths:
#             - .

#   test:
#     docker:
#       - image: cimg/node:current
#     steps:
#       - attach_workspace:
#           at: .
#       - run:
#           name: Test
#           command: npm test

# workflows:
#   version: 2
#   build_and_test:
#     jobs:
#       - build
#       - test:
#           requires:
#             - build