version: '2.1'
orbs:
  node: circleci/node@5.0.3
  aws-cli: circleci/aws-cli@3.1.4
jobs:
  test:
    executor: node/default
    steps:
      - checkout
      - run: sudo npm install -g npm@latest
      - node/install-packages:
          cache-path: ~/project/node_modules
          override-ci-command: npm install
      - run: npm run test
  deploy:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          profile-name: circleci
      - run:
          name: deploy to ec2
          command: |
            ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "cd FindYourSpace/ && git pull origin main"
workflows:
  test and deploy:
    jobs:
      - test
      - hold:
          type: approval
          requires:
            - test
      - deploy:
          requires:
            - test
            - hold
          context: aws