CREATE TABLE IF NOT EXISTS users (
  user_id SERIAL NOT NULL,
  name VARCHAR(64),
  email VARCHAR(64) NOT NULL UNIQUE,
  password VARCHAR (64),
  salt VARCHAR(64),
  is_verified BOOLEAN NOT NULL DEFAULT FALSE,
  registered_at TIMESTAMP (3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  token VARCHAR(64),
  token_expires TIMESTAMP (3),
  blueCheckmark BOOLEAN NOT NULL DEFAULT FALSE,
  PRIMARY KEY (user_id)
);