import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
// MUI default Robot font
import '@fontsource/roboto/300.css';
import '@fontsource/roboto/400.css';
import '@fontsource/roboto/500.css';
import '@fontsource/roboto/700.css';
import NavBar from "../components/navBar";
import { useSession } from 'next-auth/react';

export default function Home() {
  const { data: session } = useSession();
  console.log(session);
  return (
    <div className={styles.container}>
      <Head>
        <title>find your space</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar session={session}/>
      <main className={styles.main}>
        <h1 className={styles.title}>
          Parking made easy.
        </h1>

        <p className={styles.description}>
          (It&apos;s like Airbnb for parking spots.)
        </p>

        <div className={styles.grid}>
          <a href="" className={styles.card}>
            <h2>It&apos;s cool.</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent mattis massa eu aliquam congue.</p>
          </a>

          <a href="" className={styles.card}>
            <Image alt='' src='/../public/DALLE2_1.png' width='190' height='160'></Image>
          </a>

          <a href="" className={styles.card}>
            <Image alt='' src='/../public/DALLE2_2.png' width='190' height='160'></Image>
          </a>

          <a href="" className={styles.card}>
            <h2>Easy to use.</h2>
            <p>Proin ornare mattis augue, ac lobortis tellus sollicitudin sit amet. Curabitur sit amet maximus lectus.</p>
          </a>

          <a
            href=""
            className={styles.card}
          >
            <h2>Everyone&apos;s doing it.</h2>
            <p>Sed commodo purus ut auctor volutpat. In vehicula, nisl eu maximus tristique, neque libero luctus massa, sed finibus est leo quis eros.</p>
          </a>

          <a href="" className={styles.card}>
            <Image alt='' src='/../public/DALLE2_3.png' width='190' height='160'></Image>
          </a>

          <a href="" className={styles.card}>
            <Image alt='' src='/../public/DALLE2_4.png' width='190' height='160'></Image>
          </a>

          <a
            href=""
            target="_blank"
            rel="noopener noreferrer"
            className={styles.card}
          >
            <h2>Come on, give it a try!</h2>
            <p>
            Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Sed finibus nec risus a posuere.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a href='https://github.com/rpp2204-boc-bulbasaur/FindYourSpace'>
          Copyright &#169; 2022 Team Bulbasaur
        </a>
      </footer>
    </div>
  )
}
