import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
// MUI default Robot font
import '@fontsource/roboto/300.css';
import '@fontsource/roboto/400.css';
import '@fontsource/roboto/500.css';
import '@fontsource/roboto/700.css';
import NavBar from "../components/navBar";
import { useSession } from 'next-auth/react';
import Divider from '@mui/material/Divider';
import Box from '@mui/material/Box';
import Typography from '@mui/material/Typography';
import { createTheme, ThemeProvider } from "@mui/material/styles";

const theme = createTheme({
  palette: {
    mode: 'light',
    primary: {
      main: '#1b2139',
    },
    secondary: {
      main: '#000000',
    },
    background: {
      default: '#fbfbfb',
    },
  },
  typography: {
    fontFamily: ['Sono','sans-serif'].join(',')
  },
});

export default function Home() {
  const { data: session } = useSession();
  console.log(session);
  const scriptURL = `https://maps.googleapis.com/maps/api/js?key=${process.env.GOOGLE_MAP_API_KEY}&libraries=places&callback=initMap`

  return (
  <>
    <script id="google-map-script" async defer src={scriptURL}  />
    <div className={styles.container}>
      <Head>
        <title>find your space</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavBar session={session}/>
      <main className={styles.main}>
        <h1 className={styles.title}>Parking made easy.</h1>
        <p className={styles.description}>(It&apos;s like Airbnb for parking spots.)</p>

        <div className={styles.grid}>
          <div className={styles.card}>
            <h1>Convenient parking. Just clicks away.</h1>
            <p>Find parking spaces near you, or wherever you are going. Compare the best spots by price and distance.</p>
          </div>

          <div className={styles.card}>
            <Image alt='' src='/../public/DALLE2_1.png' width='240' height='180'></Image>
          </div>

          <div className={styles.card}>
            <Image alt='' src='/../public/DALLE2_2.png' width='240' height='180'></Image>
          </div>

          <div className={styles.card}>
            <h1>Reserve your favorite spots ahead of time.</h1>
            <p>Rent spots by the hour, day, week, or month. View your reservation history and save your favorites.</p>
          </div>

          <div className={styles.card}>
            <h1>Rent your space and earn some cash.</h1>
            <p>Have a parking spot? List your with us for hourly or monthly rentals. You control when and how to rent your space.</p>
          </div>

          <div className={styles.card}>
            <Image alt='' src='/../public/DALLE2_3.png' width='240' height='180'></Image>
          </div>
        </div>
        <Divider variant="middle" color="white"/>
        <Box>
          <h1>Testimonials</h1>
        </Box>
      </main>

      <footer className={styles.footer}>
        <a href='https://github.com/rpp2204-boc-bulbasaur/FindYourSpace'>
          Copyright &#169; 2022 Team Bulbasaur
        </a>
      </footer>
    </div>
  </>
  )
}