import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
// MUI default Robot font
import '@fontsource/roboto/300.css';
import '@fontsource/roboto/400.css';
import '@fontsource/roboto/500.css';
import '@fontsource/roboto/700.css';
import NavBar from "../components/navBar";
import { useSession } from 'next-auth/react';
import Divider from '@mui/material/Divider';
import Container from '@mui/material/Container';
import Typography from '@mui/material/Typography';
import { createTheme, ThemeProvider, responsiveFontSizes } from "@mui/material/styles";

let theme = createTheme({
  palette: {
    mode: 'light',
    primary: {
      main: '#1b2139',
    },
    secondary: {
      main: '#000000',
    },
    background: {
      default: '#fbfbfb',
    },
  },
});
theme = responsiveFontSizes(theme);

export default function Home() {
  const { data: session } = useSession();
  console.log(session);
  const scriptURL = `https://maps.googleapis.com/maps/api/js?key=${process.env.GOOGLE_MAP_API_KEY}&libraries=places&callback=initMap`

  return (
  <>
    <script id="google-map-script" async defer src={scriptURL}  />
    <div className={styles.container}>
      <Head>
        <title>find your space</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavBar session={session}/>
      <main className={styles.main}>
        <ThemeProvider theme={theme}>
          <Typography variant="h2" sx={{fontWeight: 600, display: 'flex'}}>Parking made easy.</Typography>
          <Typography variant="h5" sx={{fontWeight: 600, my: 2 }}>(It&apos;s like Airbnb for parking spots.)</Typography>

          <div className={styles.grid}>
            <div className={styles.card}>
              <Typography variant="h4" sx={{fontWeight: 600, fontFamily: 'Sono', my: 4}}>Convenient parking. Just clicks away.</Typography>
              <Typography variant="h6" sx={{ fontWeight: 400, lineHeight: 1.5 }}>
                Find parking spaces near you, or wherever you are going. Compare the best spots by price and distance.
              </Typography>
            </div>

            <div className={styles.card}>
              <Image alt='' src='/DALLE2_1.png' width='280' height='200'></Image>
            </div>

            <div className={styles.card}>
              <Image alt='' src='/DALLE2_2.png' width='280' height='200'></Image>
            </div>

            <div className={styles.card}>
              <Typography variant="h4" sx={{fontWeight: 600, fontFamily: 'Sono', my: 4}}>Reserve your favorite spots ahead of time.</Typography>
              <Typography variant="h6" sx={{ fontWeight: 400, lineHeight: 1.5 }}>
                Rent spots by the hour, day, week, or month. View your reservation history and save your favorites.
              </Typography>
            </div>

            <div className={styles.card}>
              <Typography variant="h4" sx={{fontWeight: 600, fontFamily: 'Sono', my: 4}}>Rent your space and earn some cash.</Typography>
              <Typography variant="h6" sx={{ fontWeight: 400, lineHeight: 1.5 }}>
                Have a parking spot? List your with us for hourly or monthly rentals. You control when and how to rent your space.
              </Typography>
            </div>

            <div className={styles.card}>
              <Image alt='' src='/DALLE2_3.png' width='280' height='200'></Image>
            </div>
          </div>
          <Divider variant="middle" color="white"/>
          <Typography variant="h4"
                sx={{fontWeight: 600, display: 'flex', my: 4}
              }>Testimonials
          </Typography>
          <div className={styles.grid}>
            <div className={styles.card}>
              <p>Wow I love this app so much, it&apos;s amazing! I use it for all my concerts. &mdash;Taylor Swift</p>
            </div>
            <div className={styles.card}>
              <p>OMG you guys! You did it! My parking dreams come true. &mdash;Barack Obama</p>
            </div>
            <div className={styles.card}>
              <p>I&apos;ve made so much money with this app. Try it now! &mdash;Taylor Swift</p>
            </div>
          </div>
        </ThemeProvider>
      </main>

      <footer className={styles.footer}>
        <a href='https://github.com/rpp2204-boc-bulbasaur/FindYourSpace'>
          Copyright &#169; 2022 Team Bulbasaur
        </a>
      </footer>
    </div>
  </>
  )
}